### ISSUE TITLE
Fatal error: Uncaught Error: Class 'kornrunner\Eth' not found

### ISSUE THREAD

**Issue by Maha-Blaze** [kornrunner/php-ethereum-util#3] opened 2019-01-25 09:55 UTC
Hi i am using ccxt in php.While running their exchnage i got an error Fatal error: Uncaught Error: Class 'kornrunner\Eth' not found - i have installed kornrunner using composer.Kindly help me to rectify this issue.

**Comment by kornrunner** [comment] 2019-01-25 10:43
Hi,

I suppose you're talking about [ccxt](https://github.com/ccxt/ccxt/) ?

Could you please paste some sample code to reproduce the error? Thank you.

**Comment by Maha-Blaze** [comment] 2019-01-25 10:51
Yes i am using ccxt version 1.18.141. in that base Exchange.php

<?php
namespace ccxt;

use kornrunner\Eth;
use kornrunner\Secp256k1;
use kornrunner\Solidity;
-....
...
?>
they including kornrunner. Me installed using composer.I am getting an error

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class '\kornrunner\Solidity' not found in /Exchange.php on line 2393

Fatal error: Uncaught Error: Class 'kornrunner\Eth' not found

**Comment by kornrunner** [comment] 2019-01-25 11:03
Here's something that I tried and I wasn't able to reproduce the error:

```bash
➜  ~ mkdir test
➜  ~ cd test 
➜  test composer require ccxt/ccxt 
    1/2:	http://repo.packagist.org/p/provider-2019-01$d127d618715f293bbd0e7432ee48f7862c498c7c27d1360bd2382bad02965e3a.json
    2/2:	http://repo.packagist.org/p/provider-latest$940f9bef3d66c7922ee2e987e1343076766292570c5fd988e90d723b615a6630.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
    1/2:	http://repo.packagist.org/p/provider-latest$940f9bef3d66c7922ee2e987e1343076766292570c5fd988e90d723b615a6630.json
    2/2:	http://repo.packagist.org/p/provider-2019-01$d127d618715f293bbd0e7432ee48f7862c498c7c27d1360bd2382bad02965e3a.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
    1/2:	http://repo.packagist.org/p/provider-latest$940f9bef3d66c7922ee2e987e1343076766292570c5fd988e90d723b615a6630.json
    2/2:	http://repo.packagist.org/p/provider-2019-01$d127d618715f293bbd0e7432ee48f7862c498c7c27d1360bd2382bad02965e3a.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
Using version ^1.18 for ccxt/ccxt
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
    1/11:	https://codeload.github.com/pear/Console_Table/legacy.zip/1930c11897ca61fd24b95f2f785e99e0f36dcdea
    2/11:	https://codeload.github.com/kornrunner/php-keccak/legacy.zip/ad761f528f4d1e3ce378b8a0841e5f82c9973535
    3/11:	https://codeload.github.com/simplito/bn-php/legacy.zip/e852fcd27e4acbc32459606d7606e45a85e42465
    4/11:	https://codeload.github.com/kornrunner/php-secp256k1/legacy.zip/e25345edd9bbe25ebeb744bdb772cd904d9e3998
    5/11:	https://codeload.github.com/kornrunner/php-solidity/legacy.zip/12a2af6920d24ab52b683dfbbaaf3892cbf9bd22
    6/11:	https://codeload.github.com/kornrunner/php-ethereum-util/legacy.zip/2068474206bcb94c976f094c4c8bf7e64f6cf20b
    7/11:	https://codeload.github.com/simplito/bigint-wrapper-php/legacy.zip/cf21ec76d33f103add487b3eadbd9f5033a25930
    8/11:	https://codeload.github.com/symfony/polyfill-mbstring/legacy.zip/c79c051f5b3a46be09205c73b80b346e4153e494
    9/11:	https://codeload.github.com/phpecc/phpecc/legacy.zip/b95f25cc1bacc83a9f0ccd375900b7cfd343029e
    10/11:	https://codeload.github.com/fgrosse/PHPASN1/legacy.zip/7ebf2a09084a7bbdb7b879c66fdf7ad80461bbe8
    11/11:	https://codeload.github.com/ccxt/ccxt/legacy.zip/3d334cdfefe9760277d7f035a3cb78862a295ccc
    Finished: success: 11, skipped: 0, failure: 0, total: 11
Package operations: 11 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-mbstring (v1.10.0): Loading from cache
  - Installing pear/console_table (v1.3.1): Loading from cache
  - Installing simplito/bigint-wrapper-php (1.0.0): Loading from cache
  - Installing simplito/bn-php (1.1.2): Loading from cache
  - Installing kornrunner/keccak (1.0.3): Loading from cache
  - Installing kornrunner/solidity (0.1.2): Loading from cache
  - Installing fgrosse/phpasn1 (v2.1.1): Loading from cache
  - Installing mdanter/ecc (v0.5.2): Loading from cache
  - Installing kornrunner/secp256k1 (0.1.0): Loading from cache
  - Installing kornrunner/ethereum-util (0.0.3): Loading from cache
  - Installing ccxt/ccxt (1.18.152): Loading from cache
pear/console_table suggests installing pear/Console_Color2 (>=0.1.2)
fgrosse/phpasn1 suggests installing php-curl (For loading OID information from the web if they have not bee defined statically)
Writing lock file
Generating autoload files
Changelogs summary:

 - symfony/polyfill-mbstring installed in version v1.10.0
   Release notes: https://github.com/symfony/polyfill-mbstring/releases/tag/v1.10.0

 - pear/console_table installed in version v1.3.1
   Release notes: https://github.com/pear/Console_Table/releases/tag/v1.3.1

 - simplito/bigint-wrapper-php installed in version 1.0.0
   Release notes: https://github.com/simplito/bigint-wrapper-php/releases/tag/1.0.0

 - simplito/bn-php installed in version 1.1.2
   Release notes: https://github.com/simplito/bn-php/releases/tag/1.1.2

 - kornrunner/keccak installed in version 1.0.3
   Release notes: https://github.com/kornrunner/php-keccak/releases/tag/1.0.3

 - kornrunner/solidity installed in version 0.1.2
   Release notes: https://github.com/kornrunner/php-solidity/releases/tag/0.1.2

 - fgrosse/phpasn1 installed in version v2.1.1
   Release notes: https://github.com/fgrosse/PHPASN1/releases/tag/v2.1.1

 - mdanter/ecc installed in version v0.5.2
   Release notes: https://github.com/phpecc/phpecc/releases/tag/v0.5.2

 - kornrunner/secp256k1 installed in version 0.1.0
   Release notes: https://github.com/kornrunner/php-secp256k1/releases/tag/0.1.0

 - kornrunner/ethereum-util installed in version 0.0.3
   Release notes: https://github.com/kornrunner/php-ethereum-util/releases/tag/0.0.3

 - ccxt/ccxt installed in version 1.18.152
   Release notes: https://github.com/ccxt/ccxt/releases/tag/1.18.152

➜  test nano index.php 
➜  test cat index.php 
<?php

require_once 'vendor/autoload.php';

$exchange = new ccxt\Exchange ();
var_dump ($exchange);
➜  test php index.php 
object(ccxt\Exchange)#3 (68) {
  ["curl"]=>
  resource(10) of type (curl)
  ["curl_options"]=>
  array(0) {
  }
  ["id"]=>
  NULL
  ["rateLimit"]=>
  int(2000)
  ["tokenBucket"]=>
  array(5) {
    ["refillRate"]=>
    float(0.0005)
    ["delay"]=>
    float(1)
    ["capacity"]=>
    float(1)
    ["defaultCost"]=>
    float(1)
    ["maxCapacity"]=>
    int(1000)
  }
  ["curlopt_interface"]=>
  NULL
  ["timeout"]=>
  int(10000)
  ["proxy"]=>
  string(0) ""
  ["origin"]=>
  string(1) "*"
  ["headers"]=>
  array(0) {
  }
  ["hostname"]=>
  NULL
  ["options"]=>
  array(0) {
  }
  ["skipJsonOnStatusCodes"]=>
  bool(false)
  ["name"]=>
  NULL
  ["countries"]=>
  NULL
  ["version"]=>
  NULL
  ["certified"]=>
  bool(false)
  ["urls"]=>
  array(0) {
  }
  ["api"]=>
  array(0) {
  }
  ["comment"]=>
  NULL
  ["markets"]=>
  NULL
  ["symbols"]=>
  NULL
  ["ids"]=>
  NULL
  ["currencies"]=>
  array(0) {
  }
  ["balance"]=>
  array(0) {
  }
  ["orderbooks"]=>
  array(0) {
  }
  ["fees"]=>
  array(2) {
    ["trading"]=>
    array(0) {
    }
    ["funding"]=>
    array(0) {
    }
  }
  ["precision"]=>
  array(0) {
  }
  ["limits"]=>
  array(0) {
  }
  ["orders"]=>
  array(0) {
  }
  ["trades"]=>
  array(0) {
  }
  ["transactions"]=>
  array(0) {
  }
  ["exceptions"]=>
  array(0) {
  }
  ["httpExceptions"]=>
  array(22) {
    [422]=>
    string(13) "ExchangeError"
    [418]=>
    string(14) "DDoSProtection"
    [429]=>
    string(14) "DDoSProtection"
    [404]=>
    string(20) "ExchangeNotAvailable"
    [409]=>
    string(20) "ExchangeNotAvailable"
    [500]=>
    string(20) "ExchangeNotAvailable"
    [501]=>
    string(20) "ExchangeNotAvailable"
    [502]=>
    string(20) "ExchangeNotAvailable"
    [520]=>
    string(20) "ExchangeNotAvailable"
    [521]=>
    string(20) "ExchangeNotAvailable"
    [522]=>
    string(20) "ExchangeNotAvailable"
    [525]=>
    string(20) "ExchangeNotAvailable"
    [526]=>
    string(20) "ExchangeNotAvailable"
    [400]=>
    string(20) "ExchangeNotAvailable"
    [403]=>
    string(20) "ExchangeNotAvailable"
    [405]=>
    string(20) "ExchangeNotAvailable"
    [503]=>
    string(20) "ExchangeNotAvailable"
    [530]=>
    string(20) "ExchangeNotAvailable"
    [408]=>
    string(14) "RequestTimeout"
    [504]=>
    string(14) "RequestTimeout"
    [401]=>
    string(19) "AuthenticationError"
    [511]=>
    string(19) "AuthenticationError"
  }
  ["verbose"]=>
  bool(false)
  ["apiKey"]=>
  string(0) ""
  ["secret"]=>
  string(0) ""
  ["password"]=>
  string(0) ""
  ["uid"]=>
  string(0) ""
  ["privateKey"]=>
  string(0) ""
  ["walletAddress"]=>
  string(0) ""
  ["twofa"]=>
  NULL
  ["marketsById"]=>
  NULL
  ["markets_by_id"]=>
  NULL
  ["currencies_by_id"]=>
  NULL
  ["userAgent"]=>
  NULL
  ["userAgents"]=>
  array(2) {
    ["chrome"]=>
    string(114) "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
    ["chrome39"]=>
    string(108) "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36"
  }
  ["minFundingAddressLength"]=>
  int(1)
  ["substituteCommonCurrencyCodes"]=>
  bool(true)
  ["timeframes"]=>
  NULL
  ["requiredCredentials"]=>
  array(8) {
    ["apiKey"]=>
    bool(true)
    ["secret"]=>
    bool(true)
    ["uid"]=>
    bool(false)
    ["login"]=>
    bool(false)
    ["password"]=>
    bool(false)
    ["twofa"]=>
    bool(false)
    ["privateKey"]=>
    bool(false)
    ["walletAddress"]=>
    bool(false)
  }
  ["has"]=>
  array(33) {
    ["CORS"]=>
    bool(false)
    ["publicAPI"]=>
    bool(true)
    ["privateAPI"]=>
    bool(true)
    ["cancelOrder"]=>
    bool(true)
    ["cancelOrders"]=>
    bool(false)
    ["createDepositAddress"]=>
    bool(false)
    ["createOrder"]=>
    bool(true)
    ["createMarketOrder"]=>
    bool(true)
    ["createLimitOrder"]=>
    bool(true)
    ["deposit"]=>
    bool(false)
    ["fetchBalance"]=>
    bool(true)
    ["fetchClosedOrders"]=>
    bool(false)
    ["fetchCurrencies"]=>
    bool(false)
    ["fetchDepositAddress"]=>
    bool(false)
    ["fetchDeposits"]=>
    bool(false)
    ["fetchFundingFees"]=>
    bool(false)
    ["fetchL2OrderBook"]=>
    bool(true)
    ["fetchMarkets"]=>
    bool(true)
    ["fetchMyTrades"]=>
    bool(false)
    ["fetchOHLCV"]=>
    string(8) "emulated"
    ["fetchOpenOrders"]=>
    bool(false)
    ["fetchOrder"]=>
    bool(false)
    ["fetchOrderBook"]=>
    bool(true)
    ["fetchOrderBooks"]=>
    bool(false)
    ["fetchOrders"]=>
    bool(false)
    ["fetchTicker"]=>
    bool(true)
    ["fetchTickers"]=>
    bool(false)
    ["fetchTrades"]=>
    bool(true)
    ["fetchTradingFees"]=>
    bool(false)
    ["fetchTradingLimits"]=>
    bool(false)
    ["fetchTransactions"]=>
    bool(false)
    ["fetchWithdrawals"]=>
    bool(false)
    ["withdraw"]=>
    bool(false)
  }
  ["precisionMode"]=>
  int(0)
  ["lastRestRequestTimestamp"]=>
  int(0)
  ["lastRestPollTimestamp"]=>
  int(0)
  ["restRequestQueue"]=>
  NULL
  ["restPollerLoopIsRunning"]=>
  bool(false)
  ["enableRateLimit"]=>
  bool(false)
  ["enableLastJsonResponse"]=>
  bool(true)
  ["enableLastHttpResponse"]=>
  bool(true)
  ["enableLastResponseHeaders"]=>
  bool(true)
  ["last_http_response"]=>
  NULL
  ["last_json_response"]=>
  NULL
  ["last_response_headers"]=>
  NULL
  ["requiresWeb3"]=>
  bool(false)
  ["commonCurrencies"]=>
  array(5) {
    ["XBT"]=>
    string(3) "BTC"
    ["BCC"]=>
    string(3) "BCH"
    ["DRK"]=>
    string(4) "DASH"
    ["BCHABC"]=>
    string(3) "BCH"
    ["BCHSV"]=>
    string(3) "BSV"
  }
  ["urlencode_glue"]=>
  string(1) "&"
  ["urlencode_glue_warning"]=>
  bool(true)
}
➜  test composer show
ccxt/ccxt                   1.18.152 A JavaScript / Python / PHP cryptocurrency trading library with support for more than 90 bitcoin/altcoin exchanges
fgrosse/phpasn1             v2.1.1   A PHP Framework that allows you to encode and decode arbitrary ASN.1 structures using the ITU-T X.690 Encoding Rules.
kornrunner/ethereum-util    0.0.3    Pure PHP implementation of Ethereum Utils
kornrunner/keccak           1.0.3    Pure PHP implementation of Keccak
kornrunner/secp256k1        0.1.0    Puse PHP secp256k1
kornrunner/solidity         0.1.2    Pure PHP implementation of Solidity
mdanter/ecc                 v0.5.2   PHP Elliptic Curve Cryptography library
pear/console_table          v1.3.1   Library that makes it easy to build console style tables.
simplito/bigint-wrapper-php 1.0.0    Common interface for php_gmp and php_bcmath modules
simplito/bn-php             1.1.2    Big number implementation compatible with bn.js
symfony/polyfill-mbstring   v1.10.0  Symfony polyfill for the Mbstring extension
```

Actual example of the code / script you're trying to run would help. Thanks.

**Comment by kornrunner** [comment] 2019-01-25 23:42
Since I cannot reproduce it based on how I understood you, I'll close this one. Feel free to reopen if you can provide a reproducible code snippet.

Thanks.

**Closed as completed by kornrunner** 2019-01-25 23:42 UTC
